Add web links
404busters/hkoscon-2017 pull request #116
Opened 2017-05-17 18:01 UTC by railsstudent

#111 

Add Events menu with unconference, lightning talks and global & local f/oss meeting
Please ask marketing team to review.

2017-05-17 19:09 UTC, tonyhhyip commented
Request for screen cap

2017-05-17 19:23 UTC, railsstudent commented
![selection_015](https://cloud.githubusercontent.com/assets/1159649/26171879/179fa9ca-3b79-11e7-94e0-739347d73cbe.png)
![selection_016](https://cloud.githubusercontent.com/assets/1159649/26171882/19e1f2ba-3b79-11e7-8186-c8c39dc861bc.png)
![selection_017](https://cloud.githubusercontent.com/assets/1159649/26171885/1bd254ca-3b79-11e7-8d57-e0d6a6d0e263.png)
![selection_018](https://cloud.githubusercontent.com/assets/1159649/26171893/1dd017b2-3b79-11e7-9344-0d4cfa58530b.png)

2017-05-17 19:24 UTC, railsstudent commented
![selection_019](https://cloud.githubusercontent.com/assets/1159649/26172036/89798598-3b79-11e7-8658-516af2f25ad7.png)

2017-05-17 19:50 UTC, tonyhhyip requested changes
Global & Local F/OSS Community Meeting should put in two different pages

2017-05-17 19:50 UTC, tonyhhyip commented on assets/pages/events/global-local-foss.jinja
> +        <a class="waves-effect waves-light z-depth-2 btn" href="https://goo.gl/forms/1LAG9T5VIng3w5MN2">Application of Global F/OSS Community Meeting</a>
Change to "Apply"

2017-05-19 13:59 UTC, railsstudent commented
Fixed

2017-05-19 14:00 UTC, railsstudent commented
![selection_024](https://cloud.githubusercontent.com/assets/1159649/26251032/8a3cebee-3cde-11e7-8182-f0e7f5e33c31.png)
![selection_023](https://cloud.githubusercontent.com/assets/1159649/26251035/8cee99aa-3cde-11e7-9f40-386a49d337cc.png)
![selection_022](https://cloud.githubusercontent.com/assets/1159649/26251039/8eb3580c-3cde-11e7-86e0-d6e62a1cf359.png)
![selection_021](https://cloud.githubusercontent.com/assets/1159649/26251042/903bc740-3cde-11e7-90d4-c519aa8b193e.png)
![selection_020](https://cloud.githubusercontent.com/assets/1159649/26251044/91d45194-3cde-11e7-90d7-d3ece3886917.png)

2017-05-22 01:42 UTC, tonyhhyip commented
I will put it in beta for marketing team to review for the pages

2017-05-22 02:02 UTC, tonyhhyip commented
Please rename `index.jinja` -> `unconference.jinja`

2017-05-22 15:55 UTC, railsstudent commented
Fixed.

2017-05-22 15:58 UTC, railsstudent commented
![selection_012](https://cloud.githubusercontent.com/assets/1159649/26317570/852e415c-3f4a-11e7-927c-c6cdee340e53.png)

2017-05-23 06:58 UTC, tonyhhyip requested changes

2017-05-23 06:58 UTC, tonyhhyip commented on assets/pages/events/lightning-talk.jinja
> +        <p>Lightning talks will be held in Day 1 Afternoon (3:00pm - 3:25pm).</p>
Lightning Talk is on Day 2

2017-05-23 17:59 UTC, railsstudent commented
![selection_017](https://cloud.githubusercontent.com/assets/1159649/26368564/95937334-4024-11e7-9653-30c6435c3987.png)

2017-05-24 14:57 UTC, tonyhhyip approved these changes

2017-05-24 14:57 UTC, merged