Adding details at CFP page
404busters/hkoscon-2017 pull request #12
Opened 2017-02-04 14:15 UTC by railsstudent

Related to #11
I created a second card to display details in Chinese.

2017-02-04 15:58 UTC, tonyhhyip requested changes
Please add some class for styling

2017-02-04 15:58 UTC, tonyhhyip commented on assets/pages/cfp/index.jinja
> +        <div class="card">
Add class `blue-theme` and `yellow-theme-text` for this card

2017-02-04 15:58 UTC, tonyhhyip commented on assets/pages/cfp/index.jinja
> +                        <a href="https://goo.gl/forms/fmNjTshYMZlaaKo02" target="_blank">
Add class `link`

2017-02-04 15:58 UTC, tonyhhyip commented on assets/pages/cfp/index.jinja
>                          <a href="https://goo.gl/forms/fmNjTshYMZlaaKo02" target="_blank">
Add class link

2017-02-04 16:57 UTC, railsstudent commented
Done.
Add new style.scss class to add custom style

2017-02-04 17:46 UTC, tonyhhyip requested changes
Not expected result

2017-02-04 17:46 UTC, tonyhhyip commented on assets/pages/cfp/index.jinja
> +        <div class="card blue-theme">
Please refers to https://github.com/404busters/hkoscon-2017/blob/master/assets/pages/about/coc.jinja

2017-02-04 17:46 UTC, tonyhhyip commented on assets/pages/cfp/index.jinja
> +        <div class="card blue-theme">
Please refers to https://github.com/404busters/hkoscon-2017/blob/master/assets/pages/about/coc.jinja

2017-02-04 17:46 UTC, tonyhhyip commented on assets/scss/style.scss
> +.card {
Please modified in https://github.com/404busters/hkoscon-2017/blob/master/assets/scss/elements/_card.scss

2017-02-05 14:25 UTC, tonyhhyip approved these changes
Alright, I will handle the rest

2017-02-05 14:25 UTC, merged