Financial Assistance Page under Events
404busters/hkoscon-2017 pull request #125
Opened 2017-05-19 14:32 UTC by railsstudent

#120

2017-05-19 14:33 UTC, railsstudent commented
Add marketing team to provide content. I am totally BSing here

2017-05-19 14:34 UTC, railsstudent commented
![selection_025](https://cloud.githubusercontent.com/assets/1159649/26252624/548ee934-3ce3-11e7-950b-dcae2739eb25.png)
![selection_026](https://cloud.githubusercontent.com/assets/1159649/26252625/564a6668-3ce3-11e7-81e5-e1bf08e59aa2.png)

2017-05-22 01:45 UTC, tonyhhyip commented on assets/pages/events/financial-assistance.jinja
> +        <a class="waves-effect waves-light z-depth-2 btn" href="https://docs.google.com/forms/d/e/1FAIpQLSce3Oq5hy8KNYN_RakbJWlbzzp_GpIh_pCXtyvp7SLovc-5Yg/viewform?c=0&w=1">Apply</a>
Use link: https://goo.gl/forms/rpNLFNeHQ2jPv7Uj2

2017-05-22 01:46 UTC, tonyhhyip requested changes

2017-05-22 01:46 UTC, tonyhhyip commented on assets/pages/events/financial-assistance.jinja
> +        <p>Hong Kong OpenSource Conference provides financial assistance to selected individuals to attend Hong Kong OpenSource Conference.
Please change the name to "Hong Kong Open Source Conference"

2017-05-22 16:13 UTC, railsstudent commented
![selection_013](https://cloud.githubusercontent.com/assets/1159649/26317961/ecdd23bc-3f4b-11e7-84f1-902b435f4890.png)

2017-05-23 00:18 UTC, railsstudent commented
![selection_016](https://cloud.githubusercontent.com/assets/1159649/26333457/6d7c0ca6-3f90-11e7-98a1-838ebaec59bf.png)

2017-05-23 06:33 UTC, tonyhhyip approved these changes

2017-05-23 06:34 UTC, tonyhhyip commented
As it is based on #116, need to wait for review in #116

2017-05-24 14:58 UTC, merged