Add event date and time to day 1 and day 2
404busters/hkoscon-2017 pull request #139
Opened 2017-05-25 16:03 UTC by railsstudent

#138

2017-05-25 16:07 UTC, tonyhhyip commented
I change the topic of PR to save my life in closing issue

2017-05-25 16:44 UTC, tonyhhyip requested changes
Please fix for the timezone problem

2017-05-25 16:44 UTC, tonyhhyip commented on gulp/includes/html-topic.js
> +const moment = require('moment');
Use `moment-timezone` to avoid timezone problem

2017-05-25 16:44 UTC, tonyhhyip commented on gulp/includes/html-topic.js
> +  const date = moment(startTimeslot.timeStart).format(dateFormat);
use `moment(...).tz('Asia/Hong_Kong').format(...)` to avoid timezone problem

2017-05-25 16:44 UTC, tonyhhyip commented on gulp/includes/html-topic.js
> +  const timeStart = moment(startTimeslot.timeStart).format(timeFormat);
use `moment(...).tz('Asia/Hong_Kong').format(...)` to avoid timezone problem

2017-05-25 16:44 UTC, tonyhhyip commented on gulp/includes/html-topic.js
> +  const timeEnd = moment(endTimeslot.timeEnd).format(timeFormat);
use `moment(...).tz('Asia/Hong_Kong').format(...)` to avoid timezone problem

2017-05-26 00:24 UTC, railsstudent commented
Fixed.

2017-05-26 02:18 UTC, railsstudent commented
Fixed

2017-05-26 02:52 UTC, tonyhhyip approved these changes

2017-05-26 02:52 UTC, merged