Use nunjuck template engine to render data in sponsor.yml file
404busters/hkoscon-2017 pull request #52
Opened 2017-03-30 17:45 UTC by railsstudent

#49

2017-03-31 15:14 UTC, yookoala reviewed
Possible typo in `assets/page/sponsor/partial.jinja`.

Could `sponsor.logs.img` be `sponsor.logos.img` or something else? (Or should it be here? Seems duplicate with the `p.logo` section.)

2017-03-31 15:34 UTC, yookoala commented on assets/pages/sponsor/partial.jinja
> +      {{sponsor.logs.img}}
Possible typo in assets/page/sponsor/partial.jinja.

Could sponsor.logs.img be sponsor.logos.img or something else? (Or should it be here? Seems duplicate with the p.logo section.)

2017-03-31 15:42 UTC, yookoala commented on assets/data/sponsor.yml
> +  - name:     "Gold"
To synchronize with changes in #53, this should be "Gold Sponsor" instead of "Gold".

2017-03-31 15:43 UTC, yookoala requested changes
Please rebase the commit from #53. (merge conflict now)

2017-04-01 06:57 UTC, railsstudent commented on assets/pages/sponsor/partial.jinja
> +      {{sponsor.logs.img}}
Typing error. removed now.

2017-04-01 06:57 UTC, railsstudent commented on assets/data/sponsor.yml
> +  - name:     "Gold"
Amended.

2017-04-05 13:45 UTC, railsstudent commented
are you going to merge it?
@tonyhhyip

2017-04-05 13:46 UTC, tonyhhyip commented
@railsstudent Need to wait for you to rebase it

2017-04-05 13:49 UTC, railsstudent commented
I thought I rebase it.

2017-04-05 13:50 UTC, tonyhhyip commented
Need to wait for @yookoala review

2017-04-05 13:52 UTC, railsstudent commented
i think i just rebased master to this branch.

2017-04-05 13:53 UTC, tonyhhyip commented
@railsstudent You did rebase but we need to wait for @yookoala to review

2017-04-06 02:55 UTC, yookoala approved these changes

2017-04-06 02:55 UTC, yookoala commented
Thanks Connie for the work :-)

2017-04-06 02:55 UTC, merged